#!/bin/bash

temp=$(readlink $0) #reads the symlink in node_modules/.bin which gives the relative path to the scripts/frontrunner script of this module
script_folder=$(dirname $temp) #gives the relative path from node_modules/.bin/ to the scripts dir of this module
bin_folder=$(dirname $0) #gives the absolute path of node_modules/.bin. We will need to call bin_folder/script_folder/some_script to call some_script of this module


case "$1" in
   'test')
	./scripts/check_conf_file.sh
	;;
   'apex-to-file')
	$bin_folder/$script_folder/apex-to-file
	;;
   *)
	echo "bad command"
	;;
esac
